version: '3.1'
services:
  app:
    container_name: first-service-postgresql
    image: first-service-postgresql
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
